---
  - name: week2-2
    cloudformation:
      stack_name: "Week2-2-dynamic-web-application-with-https"
      state: present
      region: "ap-northeast-1"
      disable_rollback: true
      template: "cloudformation/week2-2-dynamic-web-application-with-https.yml"
      stack_policy: "policies/stack-policy.json"
      template_parameters:
        VpcId: "{{vpc_id}}"
        Subnets: "{{subnets}}"
        AvailabilityZones: "{{availability_zones}}"
        CertificateARN: "{{cert_arn}}"
        InstanceType: "{{instance_type}}"
        ImageId: "{{image_id}}"
        KeyName: "{{key_name}}"
        HostedZoneName: "{{hosted_zone_name}}"
        RecordName: "{{record_name}}"


