Description: Dynamic-Web-Appliction
Parameters:
  RecordName:
    Type: String
    Description: Record Name in Route53
  AWSAccountId:
    Type: String
    Description: AWS Account ID
  AvailabilityZone:
    Type: String
    Description: Availability Zone
    Default: ap-northeast-1a
  VPCId:
    Type: String
    Description: VPC ID
  SubnetId:
    Type: String
    Description: Subnet ID
  ExternalCIDRIP:
    Type: String
    Description: External CIDR IP
  ImageId:
    Type: String
    Description: Image ID
  InstanceType:
    Type: String
    Description: Instance Type
    Default: t2.micro
  HostedZoneName:
    Type: String
    Description: Hosted Zone Name
  KeyName:
    Type: String
    Description: The key name for ec2 secret key

Resources:
  Profile:
    Type: AWS::IAM::InstanceProfile
    Properties:
      Path: /
      Roles:
      - Ref: Role

  Role:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - ec2.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: /
      Policies:
        - PolicyName: simple-policy
          PolicyDocument:
            Statement:
            - Effect: Allow
              Action: cloudformation:DescribeStackResource
              Resource: "*"

  SecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allowing incoming on ssh port
      VpcId: !Ref VPCId
      SecurityGroupIngress:
      - IpProtocol: tcp
        FromPort: 22
        ToPort: 22
        CidrIp: 0.0.0.0/0
      - IpProtocol: tcp
        FromPort: 8080
        ToPort: 8080
        CidrIp: !Ref ExternalCIDRIP

  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref Profile
      AvailabilityZone: !Ref AvailabilityZone
      SecurityGroupIds:
      - Ref: SecurityGroup
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SubnetId: !Ref SubnetId
      BlockDeviceMappings:
      - DeviceName: /dev/xvda
        Ebs:
          VolumeSize: 8
          VolumeType: gp2
          DeleteOnTermination: true
      KeyName: !Ref KeyName
      UserData:
        Fn::Base64:
          !Sub |
            #!/bin/bash -ex

            wget -q -O - https://pkg.jenkins.io/debian/jenkins-ci.org.key | sudo apt-key add -
            echo deb https://pkg.jenkins.io/debian-stable binary/ | sudo tee /etc/apt/sources.list.d/jenkins.list
            sudo apt-get update
            sudo apt-get install jenkins -y
            sudo systemctl start jenkins
            sudo ufw allow 8080
            sudo ufw allow OpenSSH
            yes | sudo ufw enable

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      Name: !Ref RecordName
      Type: A
      HostedZoneName: !Ref HostedZoneName
      TTL: 300
      ResourceRecords:
        - !GetAtt EC2Instance.PublicIp
