---
  - name: week2-1
    cloudformation:
      stack_name: "Week2-1-dynamic-web-application"
      state: present
      region: "ap-northeast-1"
      disable_rollback: true
      template: "cloudformation/week2-1-dynamic-web-application.yml"
      stack_policy: "policies/stack-policy.json"
      template_parameters:
        RecordName: "{{record_name}}"
        AWSAccountId: "{{aws_account_id}}"
        AvailabilityZone: "{{availability_zone}}"
        VPCId: "{{vpc_id}}"
        SubnetId: "{{subnet_id}}"
        ExternalCIDRIP: "{{external_cidr_ip}}"
        ImageId: "{{image_id}}"
        InstanceType: "{{instance_type}}"
        HostedZoneName: "{{hosted_zone_name}}"
        KeyName: "{{key_name}}"