---
  - name: week1-1
    cloudformation:
      stack_name: "Week1-1-static-website-stack"
      state: present
      region: "ap-northeast-1"
      disable_rollback: true
      template: "cloudformation/week1-1-static-website.yml"
      stack_policy: "policies/stack-policy.json"
      template_parameters:
        BucketName: "{{bucket_name}}"
        IndexDocument: "{{index_document}}"
        DNSName: "{{dns_name}}"
        HostedZoneName: "{{hosted_zone_name}}"
        HostedZoneId: "{{hosted_zone_id}}"